<?php
class AmfJaktproveSammendrag
{
	public $slippTid;
	public $egneStand;
	public $egneStokk;
	public $makkerStand;
	public $makkerStokk;
	public $situasjoner;
	public $jaktlyst;
	public $fart;
	public $stil;
	public $bredde;
	public $selvstendighet;
	public $samarbeid;
	public $reviering;
	public $vf;
	public $premiegrad;		
	public $premiegradTekst;
	public $premieringsProsent;
	
	public $starterTotalt;
	public $starterUK;
	public $starterAK;
	public $starterUKAK;
	public $starterVK;
	public $starterVKSEMIFINALE;
	public $starterVKFINALE;
	public $starterUKKVALIK;
	public $starterUKKFINALE;
	public $starterDERBYKVALIK;
	public $starterDERBYSEMIFINALE;
	public $starterDERBYFINALE;
	
	public $starterTotaltForste;
	public $starterUKForste;
	public $starterAKForste;
	public $starterUKAKForste;
	public $starterVKForste;
	public $starterVKSEMIFINALEForste;
	public $starterVKFINALEForste;
	public $starterUKKVALIKForste;
	public $starterUKKFINALEForste;
	public $starterDERBYKVALIKForste;
	public $starterDERBYSEMIFINALEForste;
	public $starterDERBYFINALEForste;
	
	public $starterTotaltAndre;
	public $starterUKAndre;
	public $starterAKAndre;
	public $starterUKAKAndre;
	public $starterVKAndre;
	public $starterVKSEMIFINALEAndre;
	public $starterVKFINALEAndre;
	public $starterUKKVALIKAndre;
	public $starterUKKFINALEAndre;
	public $starterDERBYKVALIKAndre;
	public $starterDERBYSEMIFINALEAndre;
	public $starterDERBYFINALEAndre;
	
	public $starterTotaltTredje;
	public $starterUKTredje;
	public $starterAKTredje;
	public $starterUKAKTredje;
	public $starterVKTredje;
	public $starterVKSEMIFINALETredje;
	public $starterVKFINALETredje;
	public $starterUKKVALIKTredje;
	public $starterUKKFINALETredje;
	public $starterDERBYKVALIKTredje;
	public $starterDERBYSEMIFINALETredje;
	public $starterDERBYFINALETredje;
	
	public $starterTotaltFjerde;
	public $starterUKFjerde;
	public $starterAKFjerde;
	public $starterUKAKFjerde;
	public $starterVKFjerde;
	public $starterVKSEMIFINALEFjerde;
	public $starterVKFINALEFjerde;
	public $starterUKKVALIKFjerde;
	public $starterUKKFINALEFjerde;
	public $starterDERBYKVALIKFjerde;
	public $starterDERBYSEMIFINALEFjerde;
	public $starterDERBYFINALEFjerde;
	
	public $starterTotaltFemte;
	public $starterUKFemte;
	public $starterAKFemte;
	public $starterUKAKFemte;
	public $starterVKFemte;
	public $starterVKSEMIFINALEFemte;
	public $starterVKFINALEFemte;
	public $starterUKKVALIKFemte;
	public $starterUKKFINALEFemte;
	public $starterDERBYKVALIKFemte;
	public $starterDERBYSEMIFINALEFemte;
	public $starterDERBYFINALEFemte;
	
	public $starterTotaltSjette;
	public $starterUKSjette;
	public $starterAKSjette;
	public $starterUKAKSjette;
	public $starterVKSjette;
	public $starterVKSEMIFINALESjette;
	public $starterVKFINALESjette;
	public $starterUKKVALIKSjette;
	public $starterUKKFINALESjette;
	public $starterDERBYKVALIKSjette;
	public $starterDERBYSEMIFINALESjette;
	public $starterDERBYFINALESjette;
}